server:
  port: 8081

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  path: .
  file: springboot-thmeleaf.log
  level:
    com.renren.jinkong.springbootThymeleaf.dao: trace

welcome: msg=欢迎{0}光临！

